Controllers/AlcaldiumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using inviWebApp.Models;

namespace inviWebApp.Controllers
{

    public class AlcaldiumsController : Controller
    {
        private readonly inviContext _context;

        public AlcaldiumsController(inviContext context)
        {
            _context = context;
        }

        // GET: Alcaldiums
        public async Task<IActionResult> Index()
        {
              return View(await _context.Alcaldia.ToListAsync());
        }

        // GET: Alcaldiums/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Alcaldia == null)
            {
                return NotFound();
            }

            var alcaldium = await _context.Alcaldia
                .FirstOrDefaultAsync(m => m.Nombre == id);
            if (alcaldium == null)
            {
                return NotFound();
            }

            return View(alcaldium);
        }

        // GET: Alcaldiums/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alcaldiums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Clave,Nombre,Estado,Poblacion")] Alcaldium alcaldium)
        {
            if (ModelState.IsValid)
            {
                _context.Add(alcaldium);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(alcaldium);
        }

        // GET: Alcaldiums/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Alcaldia == null)
            {
                return NotFound();
            }

            var alcaldium = await _context.Alcaldia.FindAsync(id);
            if (alcaldium == null)
            {
                return NotFound();
            }
            return View(alcaldium);
        }

        // POST: Alcaldiums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Clave,Nombre,Estado,Poblacion")] Alcaldium alcaldium)
        {
            if (id != alcaldium.Nombre)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(alcaldium);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlcaldiumExists(alcaldium.Nombre))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(alcaldium);
        }

        // GET: Alcaldiums/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Alcaldia == null)
            {
                return NotFound();
            }

            var alcaldium = await _context.Alcaldia
                .FirstOrDefaultAsync(m => m.Nombre == id);
            if (alcaldium == null)
            {
                return NotFound();
            }

            return View(alcaldium);
        }

        // POST: Alcaldiums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Alcaldia == null)
            {
                return Problem("Entity set 'inviContext.Alcaldia'  is null.");
            }
            var alcaldium = await _context.Alcaldia.FindAsync(id);
            if (alcaldium != null)
            {
                _context.Alcaldia.Remove(alcaldium);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlcaldiumExists(string id)
        {
          return _context.Alcaldia.Any(e => e.Nombre == id);
        }
    }
}

Controllers/HabitarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using inviWebApp.Models;

namespace inviWebApp.Controllers
{
    public class HabitarsController : Controller
    {
        private readonly inviContext _context;

        public HabitarsController(inviContext context)
        {
            _context = context;
        }

        // GET: Habitars
        public async Task<IActionResult> Index()
        {
            var inviContext = _context.Habitars.Include(h => h.CurpNavigation).Include(h => h.ViviendaNavigation);
            return View(await inviContext.ToListAsync());
        }

        // GET: Habitars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Habitars == null)
            {
                return NotFound();
            }

            var habitar = await _context.Habitars
                .Include(h => h.CurpNavigation)
                .Include(h => h.ViviendaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (habitar == null)
            {
                return NotFound();
            }

            return View(habitar);
        }

        // GET: Habitars/Create
        public IActionResult Create()
        {
            ViewData["Curp"] = new SelectList(_context.Propietarios, "Curp", "Curp");
            ViewData["Vivienda"] = new SelectList(_context.Vivienda, "Id", "Id");
            return View();
        }

        // POST: Habitars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Id,Curp,Vivienda")] Habitar habitar)
        {
            String CurpTemp = habitar.Curp;
            

            if (ModelState.IsValid == false)
            {
                _context.Add(habitar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Curp"] = new SelectList(_context.Propietarios, "Curp", "Curp", habitar.Curp);
            ViewData["Vivienda"] = new SelectList(_context.Vivienda, "Id", "Id", habitar.Vivienda);
            return View(habitar);
        }

        // GET: Habitars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Habitars == null)
            {
                return NotFound();
            }

            var habitar = await _context.Habitars.FindAsync(id);
            if (habitar == null)
            {
                return NotFound();
            }
            ViewData["Curp"] = new SelectList(_context.Propietarios, "Curp", "Curp", habitar.Curp);
            ViewData["Vivienda"] = new SelectList(_context.Vivienda, "Id", "Id", habitar.Vivienda);
            return View(habitar);
        }

        // POST: Habitars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Curp,Vivienda")] Habitar habitar)
        {
            if (id != habitar.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid == false)
            {
                try
                {
                    _context.Update(habitar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HabitarExists(habitar.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Curp"] = new SelectList(_context.Propietarios, "Curp", "Curp", habitar.Curp);
            ViewData["Vivienda"] = new SelectList(_context.Vivienda, "Id", "Id", habitar.Vivienda);
            return View(habitar);
        }

        // GET: Habitars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Habitars == null)
            {
                return NotFound();
            }

            var habitar = await _context.Habitars
                .Include(h => h.CurpNavigation)
                .Include(h => h.ViviendaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (habitar == null)
            {
                return NotFound();
            }

            return View(habitar);
        }

        // POST: Habitars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Habitars == null)
            {
                return Problem("Entity set 'inviContext.Habitars'  is null.");
            }
            var habitar = await _context.Habitars.FindAsync(id);
            if (habitar != null)
            {
                _context.Habitars.Remove(habitar);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HabitarExists(int id)
        {
          return _context.Habitars.Any(e => e.Id == id);
        }
    }
}

Controllers/ViviendumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using inviWebApp.Models;

namespace inviWebApp.Controllers
{
    public class ViviendumsController : Controller
    {
        private readonly inviContext _context;

        public ViviendumsController(inviContext context)
        {
            _context = context;
        }

        // GET: Viviendums
        public async Task<IActionResult> Index()
        {
            var inviContext = _context.Vivienda.Include(v => v.AlcaldiaNavigation);
            return View(await inviContext.ToListAsync());
        }

        // GET: Viviendums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vivienda == null)
            {
                return NotFound();
            }

            var viviendum = await _context.Vivienda
                .Include(v => v.AlcaldiaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (viviendum == null)
            {
                return NotFound();
            }

            return View(viviendum);
        }

        // GET: Viviendums/Create
        public IActionResult Create()
        {
            ViewData["Alcaldia"] = new SelectList(_context.Alcaldia, "Nombre", "Nombre");
            return View();
        }

        // POST: Viviendums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Dirreccion,Tipo,Alcaldia")] Viviendum viviendum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(viviendum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Alcaldia"] = new SelectList(_context.Alcaldia, "Nombre", "Nombre", viviendum.Alcaldia);
            return View(viviendum);
        }

        // GET: Viviendums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vivienda == null)
            {
                return NotFound();
            }

            var viviendum = await _context.Vivienda.FindAsync(id);
            if (viviendum == null)
            {
                return NotFound();
            }
            ViewData["Alcaldia"] = new SelectList(_context.Alcaldia, "Nombre", "Nombre", viviendum.Alcaldia);
            return View(viviendum);
        }

        // POST: Viviendums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Dirreccion,Tipo,Alcaldia")] Viviendum viviendum)
        {
            if (id != viviendum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(viviendum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ViviendumExists(viviendum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Alcaldia"] = new SelectList(_context.Alcaldia, "Nombre", "Nombre", viviendum.Alcaldia);
            return View(viviendum);
        }

        // GET: Viviendums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vivienda == null)
            {
                return NotFound();
            }

            var viviendum = await _context.Vivienda
                .Include(v => v.AlcaldiaNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (viviendum == null)
            {
                return NotFound();
            }

            return View(viviendum);
        }

        // POST: Viviendums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vivienda == null)
            {
                return Problem("Entity set 'inviContext.Vivienda'  is null.");
            }
            var viviendum = await _context.Vivienda.FindAsync(id);
            if (viviendum != null)
            {
                _context.Vivienda.Remove(viviendum);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ViviendumExists(int id)
        {
          return _context.Vivienda.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - inviWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/inviWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">INVI</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDarkDropdown" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Alcaldia
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Alcaldiums" asp-action="Index" >Consulta</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Alcaldiums" asp-action="Create">Crear</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Propietarios
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Propietarios" asp-action="Index" >Consulta</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Propietarios" asp-action="Create">Crear</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Vivienda
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Viviendums" asp-action="Index" >Consulta</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Viviendums" asp-action="Create">Crear</a></li>
                  </ul>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Habitados
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark">
                    <li><a class="dropdown-item" asp-area="" asp-controller="Habitars" asp-action="Index" >Consulta</a></li>
                    <li><a class="dropdown-item" asp-area="" asp-controller="Habitars" asp-action="Create">Crear</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - inviWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>